# Generated by Django 4.0.3 on 2024-09-04 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumer',
            name='zip_code',
            field=models.CharField(max_length=8, verbose_name='CEP'),
        ),
    ]
